# Page Info
title                                     : Eden



# App Info
ios_app_id                                : 1336038164                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
support_link                              :                                           # Enter a support link.

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A suitable, earnings and sales tracker for Envato Market authors.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ander Goig
your_link                                 : https://github.com/AnderGoig
your_city                                 : Madrid
email_address                             : support@eden-app.com
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Earnings
    description                           : Check out your total incomes and filter them by day, month or year.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Statements
    description                           : Review all your sales, author fees, purchases, withdrawals, etc.
    fontawesome_icon_name                 : list-alt

  - title                                 : Portfolio
    description                           : Take a look at your portfolio items and see how each one is doing.
    fontawesome_icon_name                 : briefcase

  - title                                 : Push Notifications
    description                           : Receive instant push notifications every time you sell an item, so you don't miss anything!
    fontawesome_icon_name                 : bell

  - title                                 : Multi-Account
    description                           : You can add multiple accounts to Eden. Allowing you to switch between your accounts very easily.
    fontawesome_icon_name                 : users

  - title                                 : Offline Mode
    description                           : You can enjoy Eden without having an active network connection. Very useful when you do not have Internet access.
    fontawesome_icon_name                 : plane

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1.0
topbar_title_color                        : "#000000"

cover_image                               : # assets/headerimage.png                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f8f8f8"

link_color                                : "#7ec549"

app_title_color                           : "#000000"
app_price_color                           : "#666666"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#7ec549"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
